/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TwoDRowSum;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  public void tests() {
    int[][] a = {
        {1,2,3,4},
        {1,1,1,1},
        {2,3,1,-2}
    };
    int[] b = {10,4,4};
    assertArrayEquals(b,App.rowSums(a));
    
    int[][] c = {
        {0,0,1},
        {1,2,1},
        {2,1,2}
    };
    int[] d = {1,4,5};
    assertArrayEquals(d,App.rowSums(c));
  }
}
